### ISSUE TITLE
No Examples

### ISSUE THREAD

**Issue by Kastlebrick** [Weebly/weebly-client-php#10]
Please provide a few working examples in your readme.md file. i.e. how to make the call (how to use the client_id, client_secret).

require 'WeeblyClient.php';
$wc = new \Weebly\WeeblyClient(...........

And a few of the following: 
GET /v1/user
GET /v1/user/sites

POST /v1/user/sites/SITE_ID/apps/APP_ID/deauthorize

GET /v1/user/sites/SITE_ID/snippet
POST /v1/user/sites/SITE_ID/snippet
DELETE /v1/user/sites/SITE_ID/snippet

GET /v1/user/sites/SITE_ID/store
PATCH /v1/user/sites/SITE_ID/store

Then it would likely also be helpful for you to reference the docs for more info.. 
'For Site and User API's visit https://dev.weebly.com/user-and-site-apis.html '

**Comment by rchen1992** [comment]
We can definitely do that! We will update the readme with some examples as soon as we can.

**Comment by Kastlebrick** [comment]
Thanks for the update @rchen1992  ..however, the examples are not working as is. 

I'll send an Email with the info. shortly.
