### ISSUE TITLE
GET requests don't reset the request method

### ISSUE THREAD

**Issue by cogentParadigm** [Weebly/weebly-client-php#8]
the CURL handler is being re-used and passing GET to makeRequest does not set CURLOPT_HTTPGET to true.

Therefore, once a POST request is made, you cannot make a GET request with the same instance

**Comment by rchen1992** [comment]
Sorry for the late response; we will be investigating this issue soon.

**Comment by bdeanindy** [comment]
Has this been resolved?

**Comment by cogentParadigm** [comment]
I am no longer working on the project which I needed this for, so I can't confirm that it works. However, the referenced fix does appear to address the issue that I initially reported.
